// Stub all lucide icons as simple span elements
const createIcon = (_name: string) => {
  return function Icon(_props: any) { return null }
}

export const AlertTriangle = createIcon('AlertTriangle')
export const ArrowUp = createIcon('ArrowUp')
export const Brain = createIcon('Brain')
export const Check = createIcon('Check')
export const CheckCircle2 = createIcon('CheckCircle2')
export const ChevronDown = createIcon('ChevronDown')
export const ChevronLeft = createIcon('ChevronLeft')
export const ChevronRight = createIcon('ChevronRight')
export const ChevronUp = createIcon('ChevronUp')
export const Circle = createIcon('Circle')
export const Clock = createIcon('Clock')
export const GitBranch = createIcon('GitBranch')
export const HelpCircle = createIcon('HelpCircle')
export const ImagePlus = createIcon('ImagePlus')
export const Layers = createIcon('Layers')
export const Loader = createIcon('Loader')
export const Loader2 = createIcon('Loader2')
export const Lock = createIcon('Lock')
export const Map = createIcon('Map')
export const MoreHorizontal = createIcon('MoreHorizontal')
export const Paperclip = createIcon('Paperclip')
export const Plus = createIcon('Plus')
export const Pause = createIcon('Pause')
export const Play = createIcon('Play')
export const Send = createIcon('Send')
export const Settings = createIcon('Settings')
export const Smartphone = createIcon('Smartphone')
export const Square = createIcon('Square')
export const Target = createIcon('Target')
export const SquarePen = createIcon('SquarePen')
export const X = createIcon('X')
